# 붓꽃

## 라이브러리 정리

In [65]:
from sklearn.datasets import load_iris                      # 데이터셋 로드
from sklearn.tree import DecisionTreeClassifier             # 의사결정나무를 활용한 분류 모듈
from sklearn.model_selection import train_test_split        # 훈련-검증 데이터셋 분리 모듈
from sklearn.metrics import accuracy_score                  # 모델 성능 평가 모듈

## 데이터 준비

In [66]:
iris = load_iris()

iris_data = iris.data
print('iris feature값: \n',iris_data)
iris_label = iris.target
print('iris target값 \n',iris_label)
print('iris target명 \n',iris.target_names)

iris feature값: 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 

## 데이터셋 분리

### train_test_split(x,y,test_size=f,random=state=n): 입력, 타겟, 테스트데이터비율(실수로 표현),random_state=n(seed값 고정과 같은 의미)

In [67]:
X_train, X_test, y_train, y_test = train_test_split(iris_data,iris_label,
                                                    test_size=0.2,random_state=11)

In [68]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

### 분리한 데이터 살펴보기

In [69]:
# 아이리스 데이터 살펴보기
len(iris), len(iris_data), len(iris_label)

(8, 150, 150)

In [70]:
# 분리한 데이터 확인
len(X_train), len(y_train), len(X_test), len(y_test)

(120, 120, 30, 30)

In [71]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

### 머신러닝에 사용될 데이터 타입 확인

In [72]:
# 데이터 타입 확인: **** 머신러닝에 사용되는 데이터들은 넘파이어레이로 들어가야 문제 x
type(X_test)

numpy.ndarray

# 머신러닝 - Decision Tree

In [73]:
df_clf = DecisionTreeClassifier(random_state=11)        # 사용할 알고리즘 선언
df_clf.fit(X_train,y_train)                             # fit함수를 사용해 모델 학습
pred = df_clf.predict(X_test)                           # 학습 완료된 모델에 테스트 데이터를 넣어 예측한 타겟 도출

accuracy_score(y_test,pred)                             # 검증 타겟과 모델이 예측한 타겟 비교하여 정확도 측정

0.9333333333333333

# Model Selection 모듈

## 교차검증

### 교차검증을 위한 기본 머신러닝 수행

In [74]:
from sklearn.datasets import load_iris                      # 데이터셋 로드
from sklearn.tree import DecisionTreeClassifier             # 의사결정나무를 활용한 분류 모듈
from sklearn.model_selection import train_test_split        # 훈련-검증 데이터셋 분리 모듈
from sklearn.metrics import accuracy_score                  # 모델 성능 평가 모듈

df_clf = DecisionTreeClassifier()
iris_data = load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris_data.data,iris_data.target,
                                                    test_size=0.3,random_state=121)

In [75]:
df_clf.fit(X_train,y_train)
pred = df_clf.predict(X_test)
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

예측 정확도: 0.9556


### 1. K 폴드
* from sklearn.model_selection import KFold

In [76]:
# 데이터 준비
from sklearn.model_selection import KFold

iris=load_iris()
features = iris.data                                # 분리를 해야하는 데이터 값들, *** type = numpy.ndarray
label = iris.target
df_clf = DecisionTreeClassifier(random_state=156)   # 머신러닝 알고리즘, 아직 학습 X

k_ford = KFold(n_splits=5)                          # KFold 기능을 담는 변수
cv_accuracy = []                                    

print('붓꽃 데이터 세트 크기: ',features.shape[0])

붓꽃 데이터 세트 크기:  150


In [77]:
print(type(features),type(label))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


#### Kfold(n_splits=n).split(분리할 데이터): 데이터 n개로 분리
* n_splits = : 분리되어서 나올 데이터셋이 몇 개인지 설정

##### 나

In [78]:
n_iter = 0
cv_accuracy = []                # 머신러닝 학습을 n번 하고 정확도 각각을 내서 평균낼 거니까 정확도 n개 담을 리스트 준비

for train_index, test_index in KFold(n_splits=5).split(features):       #k_fold 변수가 작동 안해서 그냥 내용물 넣어버림
    # 훈련 세트와 테스트 세트 데이터 설정, train_test_split은 리턴값이 4개이기 때문에 이 경우에 사용할 수 없다
    train_X = features[train_index]
    test_X = features[test_index]
    train_y = label[train_index]
    test_y = label[test_index]
        
    df_clf.fit(train_X,train_y)                         # 머신러닝 알고리즘 학습
    cv_accuracy.append(df_clf.score(test_X,test_y))     # 각각의 정확도 리스트에 담기
print(cv_accuracy)
    

[1.0, 0.9666666666666667, 0.8666666666666667, 0.9333333333333333, 0.7333333333333333]


In [79]:
import numpy as np

cv_accuracy_mean = np.mean(cv_accuracy)
print(cv_accuracy_mean)

0.9


##### 교수님 버전

In [80]:
n_iter = 0
cv_accuracy = []                # 머신러닝 학습을 n번 하고 정확도 각각을 내서 평균낼 거니까 정확도 n개 담을 리스트 준비

for train_index, test_index in KFold(n_splits=5).split(features):       #k_fold 변수가 작동 안해서 그냥 내용물 넣어버림
    n_iter += 1
    # 훈련 세트와 테스트 세트 데이터 설정, train_test_split은 리턴값이 4개이기 때문에 이 경우에 사용할 수 없다
    train_X = features[train_index]
    test_X = features[test_index]
    train_y = label[train_index]
    test_y = label[test_index]
    
    # 머신러닝 알고리즘 학습    
    df_clf.fit(train_X,train_y)
    pred = df_clf.predict(test_X)
    
    # 학습된 머신러닝 모델 성능 평가
    accuracy = np.round(accuracy_score(test_y, pred),4)
    cv_accuracy.append(accuracy)     # 각각의 정확도 리스트에 담기
    
    # 결과 이쁘게 보기
    train_size = train_X.shape[0]
    test_size = test_X.shape[0]
    print('"\n" {0}교차 검증 정확도: {1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'.format(n_iter,accuracy,train_size,test_size))
    
    
print(f'평균 정확도: {np.mean(cv_accuracy)}')
    

"
" 1교차 검증 정확도: 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
"
" 2교차 검증 정확도: 0.9667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
"
" 3교차 검증 정확도: 0.8667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
"
" 4교차 검증 정확도: 0.9333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
"
" 5교차 검증 정확도: 0.7333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
평균 정확도: 0.9


### 2. Stratfied K폴드 : kfold의 문제점 개선

In [81]:
# 데이터 준비
import pandas as pd

iris = load_iris()
iris_df = pd.DataFrame(iris.data,columns=(iris.feature_names))
iris_df['label'] = iris.target
iris_df['label'].value_counts()

label
0    50
1    50
2    50
Name: count, dtype: int64

#### * k fold가 문제되는 경우: y값들이 몇 개 없고 덩어리져있을 때

In [82]:
n_iter = 0
cv_accuracy = []                # 머신러닝 학습을 n번 하고 정확도 각각을 내서 평균낼 거니까 정확도 n개 담을 리스트 준비

for train_index, test_index in KFold(n_splits=3).split(iris_df):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    
    print(f'교차검증: {n_iter}')
    print('학습 레이블 데이터 분포',label_train.value_counts())
    print('검증 레이블 데이터 분포',label_test.value_counts())

교차검증: 1
학습 레이블 데이터 분포 label
1    50
2    50
Name: count, dtype: int64
검증 레이블 데이터 분포 label
0    50
Name: count, dtype: int64
교차검증: 2
학습 레이블 데이터 분포 label
0    50
2    50
Name: count, dtype: int64
검증 레이블 데이터 분포 label
1    50
Name: count, dtype: int64
교차검증: 3
학습 레이블 데이터 분포 label
0    50
1    50
Name: count, dtype: int64
검증 레이블 데이터 분포 label
2    50
Name: count, dtype: int64


#### stratfied kfold 수행: y값을 기준으로 고르게 섞임

In [83]:
from sklearn.model_selection import StratifiedKFold

clf = StratifiedKFold(n_splits=3)

n_iter = 0
cv_accuracy = []

for train_index, test_index in clf.split(iris_df,iris_df['label']):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    
    print(f'교차검증: {n_iter}')
    print('학습 레이블 데이터 분포',label_train.value_counts())
    print('검증 레이블 데이터 분포',label_test.value_counts())
    print(test_index)
    print()

교차검증: 1
학습 레이블 데이터 분포 label
2    34
0    33
1    33
Name: count, dtype: int64
검증 레이블 데이터 분포 label
0    17
1    17
2    16
Name: count, dtype: int64
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

교차검증: 2
학습 레이블 데이터 분포 label
1    34
0    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포 label
0    17
2    17
1    16
Name: count, dtype: int64
[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

교차검증: 3
학습 레이블 데이터 분포 label
0    34
1    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포 label
1    17
2    17
0    16
Name: count, dtype: int64
[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135


In [84]:
from sklearn.model_selection import StratifiedKFold

clf = StratifiedKFold(n_splits=3)

n_iter = 0
cv_accuracy = []

for train_index, test_index in clf.split(iris_df,iris_df['label']):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    
    print(f'교차검증: {n_iter}')
    print('학습 레이블 데이터 분포',label_train.value_counts())
    print('검증 레이블 데이터 분포',label_test.value_counts())
    print(test_index)
    print()

교차검증: 1
학습 레이블 데이터 분포 label
2    34
0    33
1    33
Name: count, dtype: int64
검증 레이블 데이터 분포 label
0    17
1    17
2    16
Name: count, dtype: int64
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

교차검증: 2
학습 레이블 데이터 분포 label
1    34
0    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포 label
0    17
2    17
1    16
Name: count, dtype: int64
[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

교차검증: 3
학습 레이블 데이터 분포 label
0    34
1    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포 label
1    17
2    17
0    16
Name: count, dtype: int64
[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135


#### 위에서 했던 거랑 같은 kfold 를 stratfied로 진행
* 변경 1: KFold(n_splits) -> StratfiedKFold(n_splits)
* 변경 2: cv_accuracy -> cv_accuracyS

In [85]:
clf = StratifiedKFold(n_splits=3)

n_iter = 0
cv_accuracyS = []

for train_index, test_index in StratifiedKFold(n_splits=5).split(features,label):
    n_iter += 1
    
    train_X = features[train_index]
    test_X = features[test_index]
    train_y = label[train_index]
    test_y = label[test_index]
    
    # 머신러닝 알고리즘 학습    
    df_clf.fit(train_X,train_y)
    pred = df_clf.predict(test_X)
    
    # 학습된 머신러닝 모델 성능 평가
    accuracy = np.round(accuracy_score(test_y, pred),4)
    cv_accuracyS.append(accuracy)
    
    # 결과 이쁘게 보기
    train_size = train_X.shape[0]
    test_size = test_X.shape[0]
    print('"\n" {0}교차 검증 정확도: {1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'.format(n_iter,accuracy,train_size,test_size))
    
    
print(f'평균 정확도: {np.mean(cv_accuracyS)}')

"
" 1교차 검증 정확도: 0.9667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
"
" 2교차 검증 정확도: 0.9667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
"
" 3교차 검증 정확도: 0.9, 학습 데이터 크기: 120, 검증 데이터 크기: 30
"
" 4교차 검증 정확도: 0.9667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
"
" 5교차 검증 정확도: 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
평균 정확도: 0.9600200000000001


### 3. cross_val_score()

In [86]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

df_clf = DecisionTreeClassifier(random_state=156)
iris_data = load_iris()

data = iris_data.data
label = iris_data.target

scores = cross_val_score(df_clf, data, label, scoring='accuracy',cv = 3)        # 이 한 줄이 메인
print('교차 검증별 정확도: ',np.round(scores,5))
print('평균 검증 정확도: ',np.round(np.mean(scores),4))

교차 검증별 정확도:  [0.98 0.94 0.98]
평균 검증 정확도:  0.9667


### 4. GridSearchCV(교차검증 + 하이퍼 파라미터 튜닝)

In [90]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris

iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data,iris.target,
                                                    test_size=0.2,random_state=121)

dtree = DecisionTreeClassifier()
print(id(dtree))

parameters = {'max_depth':[1,2,3],'min_samples_split':[2,3]}
# depth : 자식 노드의 층위 수

4545811728


In [91]:
import pandas as pd

grid_df_clf = GridSearchCV(dtree,param_grid=parameters,cv=3,refit=True)     # refit속성: 이따 더 찾아보기
grid_df_clf.fit(X_train,y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]})

In [96]:
import pandas as pd

grid_dtree = GridSearchCV(dtree,param_grid = parameters,cv=3, refit=True)
grid_dtree.fit(X_train,y_train)

scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score','rank_test_score','split0_test_score','split1_test_score','split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [97]:
scores_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.001519      0.000479         0.001122        0.000502   
1       0.000776      0.000115         0.000589        0.000030   
2       0.000850      0.000227         0.000685        0.000227   
3       0.001832      0.000246         0.001260        0.000334   
4       0.001080      0.000188         0.000758        0.000027   
5       0.000640      0.000026         0.000549        0.000086   

  param_max_depth param_min_samples_split  \
0               1                       2   
1               1                       3   
2               2                       2   
3               2                       3   
4               3                       2   
5               3                       3   

                                     params  split0_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}              0.700   
1  {'max_depth': 1, 'min_samples_split': 3}              0.700   
2  {'max_depth': 2, 'min_samples_split': 2}              0.925   
3  {'max_depth': 2, 'min_samples_split': 3}              0.925   
4  {'max_depth': 3, 'min_samples_split': 2}              0.975   
5  {'max_depth': 3, 'min_samples_split': 3}              0.975   

   split1_test_score  split2_test_score  mean_test_score  std_test_score  \
0                0.7               0.70         0.700000    1.110223e-16   
1                0.7               0.70         0.700000    1.110223e-16   
2                1.0               0.95         0.958333    3.118048e-02   
3                1.0               0.95         0.958333    3.118048e-02   
4                1.0               0.95         0.975000    2.041241e-02   
5                1.0               0.95         0.975000    2.041241e-02   

   rank_test_score  
0                5  
1                5  
2                3  
3                3  
4                1  
5                1