# 데이터 인코딩

## 레이블 인코딩

In [1]:
from sklearn.preprocessing import LabelEncoder

items = ['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값: ',labels)

인코딩 변환값:  [0 1 4 5 3 3 2 2]


In [2]:
print('인코딩 클래스: ', encoder.classes_)

인코딩 클래스:  ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [4]:
print('디코딩된 값: ', encoder.inverse_transform([0, 1, 4, 5, 3, 3, 2, 2]))

디코딩된 값:  ['TV' '냉장고' '전자렌지' '컴퓨터' '선풍기' '선풍기' '믹서' '믹서']


## 원-핫 인코딩
레이블 인코딩을 해야 원-핫 인코딩을 할 수 있음

* 방법 1:  sklearn 라이브러리 OneHotEncoder 사용

In [5]:
from sklearn.preprocessing import LabelEncoder

items = ['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

# LabelEncoder로 변환
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [7]:
# .reshape() : 2차원 데이터로 변환
labels = labels.reshape(-1,1)       # reshape(-1,1) 해석: 행은 상관없고 열은 1열로
labels

array([[0],
       [1],
       [4],
       [5],
       [3],
       [3],
       [2],
       [2]])

In [11]:
# 원-핫 인코딩 적용
from sklearn.preprocessing import OneHotEncoder

oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)

oh_labels = oh_encoder.transform(labels)
print(oh_labels)

print(oh_labels.toarray())
print(oh_labels.shape)

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 4)	1.0
  (3, 5)	1.0
  (4, 3)	1.0
  (5, 3)	1.0
  (6, 2)	1.0
  (7, 2)	1.0
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
(8, 6)


* 방법 2:  pandas의 get_dummies 활용

In [12]:
import pandas as pd

df = pd.DataFrame({'item':['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자렌지  item_컴퓨터
0     True     False    False     False      False     False
1    False      True    False     False      False     False
2    False     False    False     False       True     False
3    False     False    False     False      False      True
4    False     False    False      True      False     False
5    False     False    False      True      False     False
6    False     False     True     False      False     False
7    False     False     True     False      False     False

# 피쳐 스케일링과 정규화

In [13]:
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
iris_df = pd.DataFrame(data = iris.data, columns = iris.feature_names)
print('feature들의 평균 값')
print(iris_df.mean())
print('feature들의 분산 값')
print(iris_df.var())


feature들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
feature들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


## StandardScaler: 표준화

In [14]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature들의 평균 값: ')
print(iris_df_scaled.mean())
print('feature들의 분산 값: ')
print(iris_df_scaled.var())

feature들의 평균 값: 
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
feature들의 분산 값: 
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


## MinMaxScaler: 정규화

In [15]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled,columns=iris.feature_names)
print('feature들의 평균 값')
print(iris_df_scaled.mean())
print('feature들의 분산 값')
print(iris_df_scaled.var())

feature들의 평균 값
sepal length (cm)    0.428704
sepal width (cm)     0.440556
petal length (cm)    0.467458
petal width (cm)     0.458056
dtype: float64
feature들의 분산 값
sepal length (cm)    0.052908
sepal width (cm)     0.032983
petal length (cm)    0.089522
petal width (cm)     0.100869
dtype: float64


## * 주의사항

In [17]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

train_array = np.arange(0,11).reshape(-1,1)
test_array = np.arange(0,6).reshape(-1,1)

### * 오류가 있는 코드

In [18]:
scaler = MinMaxScaler()

scaler.fit(train_array)
train_scaled = scaler.transform(train_array)

print('원본 train_array 데이터: ',np.round(train_array.reshape(-1),2))
print('scaled train_array 데이터: ', np.round(train_scaled.reshape(-1),2))


원본 train_array 데이터:  [ 0  1  2  3  4  5  6  7  8  9 10]
scaled train_array 데이터:  [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [20]:
scaler.fit(test_array)
test_scaled = scaler.transform(test_array)

print('원본 test_array 데이터: ',np.round(test_array.reshape(-1),2))
print('scaled test_array 데이터: ', np.round(test_scaled.reshape(-1),2))

원본 test_array 데이터:  [0 1 2 3 4 5]
scaled test_array 데이터:  [0.  0.2 0.4 0.6 0.8 1. ]


### * 정상 코드

In [21]:
scaler = MinMaxScaler()

scaler.fit(train_array)             # scaler.fit() : 이 코드가 스케일링의 범위를 지정하는 코드
train_scaled = scaler.transform(train_array)

print('원본 train_array 데이터: ',np.round(train_array.reshape(-1),2))
print('scaled train_array 데이터: ', np.round(train_scaled.reshape(-1),2))

# scaler.fit(test_array)                            # 주석 처리한 이 부분을 동일하게 적용해주어야 함
test_scaled = scaler.transform(test_array)

print('원본 test_array 데이터: ',np.round(test_array.reshape(-1),2))
print('scaled test_array 데이터: ', np.round(test_scaled.reshape(-1),2))

원본 train_array 데이터:  [ 0  1  2  3  4  5  6  7  8  9 10]
scaled train_array 데이터:  [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
원본 test_array 데이터:  [0 1 2 3 4 5]
scaled test_array 데이터:  [0.  0.1 0.2 0.3 0.4 0.5]
